### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.tune.TuneTracker" on path

### ISSUE THREAD

**Issue by turkenh** [MobileAppTracking/unity-plugin#7]
I am using Tune unity plugin for my android game. 
When I install it via apk file, everything works fine. But when I try to install via playstore, my game crashes at first launch with the following crash logs:

```
java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 5.3.4f1
Device model      : samsung GT-I9500
Device fingerprint: samsung/ja3gxx/ja3g:5.0.1/LRX22C/I9500XXUHOL1:user/release-keys
Caused by: java.lang.RuntimeException: Unable to instantiate receiver com.tune.TuneTracker: java.lang.ClassNotFoundException: Didn't find class "com.tune.TuneTracker" on path: DexPathList[[zip file "/data/app/fab.gameofwords-1/base.apk"],nativeLibraryDirectories=[/data/app/fab.gameofwords-1/lib/arm, /vendor/lib, /system/lib]]
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2983)
	at android.app.ActivityThread.access$1800(ActivityThread.java:177)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1526)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5951)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tune.TuneTracker" on path: DexPathList[[zip file "/data/app/fab.gameofwords-1/base.apk"],nativeLibraryDirectories=[/data/app/fab.gameofwords-1/lib/arm, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2978)
	... 9 more
	Suppressed: java.lang.ClassNotFoundException: com.tune.TuneTracker
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 11 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

Here is my AndroidManifest.xml

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="fab.gameofwords" android:installLocation="preferExternal" android:theme="@android:style/Theme.NoTitleBar" android:versionCode="1" android:versionName="1.0">
	<supports-screens android:smallScreens="true" android:normalScreens="true" android:largeScreens="true" android:xlargeScreens="true" android:anyDensity="true" />
	<application android:icon="@drawable/app_icon" android:label="@string/app_name" android:debuggable="true">
		<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
		<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="fb577464905719222" />
		<provider android:name="android.support.v4.content.FileProvider" android:authorities="fab.gameofwords.fileprovider" android:exported="false" android:grantUriPermissions="true">
			<meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths" />
		</provider>
		<activity android:name="com.unity3d.player.UnityPlayerNativeActivity" android:label="@string/app_name">
			<meta-data android:name="unityplayer.UnityActivity" android:value="true" />
			<meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="true" />
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
		<activity android:name="com.facebook.unity.FBUnityLoginActivity" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
		<activity android:name="com.facebook.unity.FBUnityDialogsActivity" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
		<activity android:name="com.facebook.LoginActivity" android:configChanges="keyboardHidden|orientation" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
		<activity android:name="com.facebook.unity.FBUnityDeepLinkingActivity" android:exported="true" />
		<activity android:name="com.google.android.gms.ads.AdActivity" android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" android:theme="@android:style/Theme.Translucent" />
		<activity android:name="com.androidnative.AndroidNativeProxy" android:launchMode="singleTask" android:label="@string/app_name" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:theme="@android:style/Theme.Translucent.NoTitleBar">
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.DEFAULT" />
				<category android:name="android.intent.category.BROWSABLE" />
				<data android:scheme="oauth" android:host="fab.gameofwords" />
			</intent-filter>
		</activity>
		<activity android:name="com.outlinegames.unibill.PurchaseActivity" android:label="@string/app_name" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:screenOrientation="portrait" />
		<!--Parse-->
		<receiver android:name="com.parse.ParsePushBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">
			<intent-filter>
				<action android:name="com.google.android.c2dm.intent.RECEIVE" />
				<action android:name="com.google.android.c2dm.intent.REGISTRATION" />
				<category android:name="fab.gameofwords" />
			</intent-filter>
		</receiver>
		<service android:name="com.parse.ParsePushService" />
		<!--End-->
		<!--Google Analytics-->
		<service android:name="com.google.analytics.tracking.android.CampaignTrackingService" />
		<receiver android:name="com.google.analytics.tracking.android.CampaignTrackingReceiver" android:exported="true">
			<intent-filter>
				<action android:name="com.android.vending.INSTALL_REFERRER" />
			</intent-filter>
		</receiver>
		<!--End-->
		<activity android:name="com.outlinegames.unibill.PurchaseActivity" android:label="@string/app_name" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
		<activity android:name="com.facebook.unity.FBUnityAppLinkActivity" android:exported="true" />
		<activity android:name="com.facebook.unity.FBUnityGameRequestActivity" />
		<activity android:name="com.facebook.unity.FBUnityCreateGameGroupActivity" />
		<activity android:name="com.facebook.unity.FBUnityJoinGameGroupActivity" />
		<activity android:name="com.facebook.unity.AppInviteDialogActivity" />
		<provider android:name="com.facebook.FacebookContentProvider" android:authorities="com.facebook.app.FacebookContentProvider577464905719222" android:exported="true" />
		<activity android:name="com.facebook.FacebookActivity" android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:label="@string/app_name" android:theme="@android:style/Theme.Translucent.NoTitleBar" />
		<receiver android:name="com.tune.TuneTracker" android:exported="true">
			<intent-filter>
				<action android:name="com.android.vending.INSTALL_REFERRER" />
			</intent-filter>
		</receiver>
		<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
	</application>
	<!-- Settings for GCM -->
	<permission android:name="fab.gameofwords.permission.C2D_MESSAGE" android:protectionLevel="signature" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.WAKE_LOCK" />
	<uses-permission android:name="android.permission.VIBRATE" />
	<uses-permission android:name="android.permission.GET_ACCOUNTS" />
	<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
	<uses-permission android:name="fab.gameofwords.permission.C2D_MESSAGE" />
	<uses-permission android:name="com.android.vending.BILLING" />
</manifest>
```

What can be wrong, what am I missing?
Read something related to proguard, but there is no such setting in Unity....

**Comment by john-gu** [comment]
Hi @turkenh, can you confirm that you have `TuneMarketingConsoleSDK-x.y.z.jar` in `Plugins/Android/`, and have removed any previous `MobileAppTracker-x.y.z.jar` file?

**Comment by turkenh** [comment]
Hi @john-gu, in fact, there is MobileAppTracker-3.11.4.jar and just realized that you have newer releases which includes some changes related to files you mentioned.
I think, first I need to upgrade and recheck, right?
Will update here once done.

Thanks for fast response :)

**Comment by john-gu** [comment]
@turkenh In that case, please consult our upgrade guide to help you get your Unity installation updated:
https://developers.mobileapptracking.com/migrating-sdk-from-3-x-x-to-4-x-x/

**Comment by turkenh** [comment]
After updating plugin to the latest unity package, error seems to gone. 
Thank you @john-gu ...
